name: Build AAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 29
          build-tools: '34.0.0'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build AAR
        run: ./gradlew :app:assembleRelease

      - name: Upload AAR
        uses: actions/upload-artifact@v3
        with:
          name: aar-file
          path: app/build/outputs/aar/*.aar
